kind: ConfigMap 
apiVersion: v1 
metadata:
  name: chart-values 
data:
  install: "true"
  repo: "https://raw.githubusercontent.com/kubernetes-sigs/kubefed/master/charts"
  version: "0.1.0-rc6"
  chart: "kubefed"
  values.yaml: | 
    controllermanager:
      enabled: true
      replicaCount: 2
      repository: quay.io/kubernetes-multicluster
      image: kubefed
      tag: canary
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      clusterAvailableDelay:
      clusterUnavailableDelay:
      leaderElectLeaseDuration:
      leaderElectRenewDeadline:
      leaderElectRetryPeriod:
      clusterHealthCheckPeriod:
      clusterHealthCheckFailureThreshold:
      clusterHealthCheckSuccessThreshold:
      clusterHealthCheckTimeout:
      leaderElectResourceLock:
      syncController:
        adoptResources:
      featureGates:
        PushReconciler:
        SchedulerPreferences:
        CrossClusterServiceDiscovery:
        FederatedIngress:
    global:
      ## The scope of the the kubefed control plane.  Supported options
      ## are `Cluster` (watch cluster-scoped resources and resources in
      ## all namespaces) and `Namespaced` (only watch resources in the
      ## kubefed system namespace). If unset, will default to `Cluster`.
      scope: ""